
import { Inter } from 'next/font/google'
import './globals.css'
import Layout from './components/Layout'
import { StateContext } from './context/StateContext'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StateContext>
        <body className="flex flex-col text-gray-900 overflow-x-hidden">
          <section className={inter.className}>
              <Layout>
                {children}
              </Layout>
          </section>
        </body>
      </StateContext>
    </html>
  )
}
